jQuery(document).ready(function($){$("ul.tabbed_nav").tabs(".tabbed_container .tabbed_content",{effect:'fade',fadeOutSpeed:400});$(".custom_tabs").tabs(".custom_tabs_content",{tabs:"li",effect:'fade'});$(".custom_tabs2").tabs(".custom_tabs2_content",{tabs:"li",effect:'fade'});$('.scrollTo_top').hide();$(window).scroll(function(){if($(this).scrollTop()>100){$('.scrollTo_top').fadeIn(300);}
else{$('.scrollTo_top').fadeOut(300);}});$('.scrollTo_top a').click(function(){$('html, body').animate({scrollTop:0},500);return false;});jQuery("#navigation ul.nav a, .top_bar ul.top_nav a").removeAttr('title');jQuery(" #navigation ul.nav ul, .top_bar ul.top_nav ul").css({display:"none"});jQuery("#navigation ul.nav li, .top_bar ul.top_nav li").each(function()
{var jQuerysubmeun=jQuery(this).find('ul:first');jQuery(this).hover(function()
{jQuerysubmeun.stop().css({overflow:"hidden",height:"auto",display:"none",paddingTop:0}).slideDown(250,function()
{jQuery(this).css({overflow:"visible",height:"auto"});});},function()
{jQuerysubmeun.stop().slideUp(250,function()
{jQuery(this).css({overflow:"hidden",display:"none"});});});});$('.lates_video_item a ').hover(function(){$(this).find('span.video_icon, span.slide_icon').stop().animate({left:0},{queue:false,duration:200});},function(){$(this).find('span.video_icon, span.slide_icon').stop().animate({left:'-44px'},{queue:false,duration:200});});$('.recent_news_img a').hover(function(){$(this).find('.nb_video_icon, .nb_slide_icon, .nb_article_icon ').stop().animate({left:0},{queue:false,duration:200});},function(){$(this).find('.nb_video_icon, .nb_slide_icon, .nb_article_icon ').stop().animate({left:'-44px'},{queue:false,duration:200});});$('.cat_img a').hover(function(){$(this).find('.ca_video_icon, .ca_slide_icon, .ca_article_icon').stop().animate({left:0},{queue:false,duration:200});},function(){$(this).find('.ca_video_icon, .ca_slide_icon, .ca_article_icon').stop().animate({left:'-44px'},{queue:false,duration:200});});$('.cat_article_img img, .widget .flickr_badge_wrapper a, .news_box .recent_news_img, .mom_posts_images img, ul.blog_posts_widget li img, .lates_video_item img, .sidebar .ads125 img, .related_image, .nb2_next2_img img, .nbtabs_content li .nt_image img, .news_pictures .news_pictures_list li img').hover(function(){$(this).stop().animate({opacity:0.8},{queue:false,duration:200});},function(){$(this).stop().animate({opacity:1},{queue:false,duration:200});});$('.single_article_content .flickr_badge_wrapper div img, a.lightbox_img img').hover(function(){$(this).stop().animate({opacity:0.7},{queue:false,duration:200});},function(){$(this).stop().animate({opacity:1},{queue:false,duration:200});});$("a.lightbox_img").prettyPhoto({deeplinking:false});$(".gallery .gallery-item .gallery-icon a").attr('rel','prettyPhoto[mom_gal]');$(".gallery .gallery-item .gallery-icon a").prettyPhoto({deeplinking:false});$(".mom_gallery .gallery-item .gallery-icon a").prettyPhoto({deeplinking:false});$(".accordion").tabs(".accordion .acc_content",{tabs:'h2.acc_title',effect:'slide',initialIndex:null});$('.accordion .acc_title:first-child').addClass('current');$('.accordion .acc_title.current').next('div.acc_content').css('display','block');jQuery("h4.toggle").click(function(){$(this).next(".toggle_content").slideToggle();$(this).toggleClass("active_toggle");$(this).parent().toggleClass("toggle_var");});$("h4.toggle_min").click(function(){$(this).next(".toggle_content_min").slideToggle();$(this).toggleClass("active_toggle_min");});$('.news_pictures .news_pictures_list li a').tipsy({gravity:'s',fade:true});$('.news_pictures_list li a').tipsy({gravity:'s',fade:true});if(jQuery.browser.msie){if(parseFloat(jQuery.browser.version)<9){}
else{}}
else{$('.bottom_bar ul.social_icons li a').hover(function(){$(this).stop().animate({opacity:0.6},{queue:false,duration:200});},function(){$(this).stop().animate({opacity:1},{queue:false,duration:200});});}
$(".navi_links").show();$(".navi_links a:first").addClass("active");var imageWidth=$(".scrollable").width();var imageSum=$(".scroll_items img").size();var imageReelWidth=imageWidth*imageSum;$(".scroll_items").css({'width':imageReelWidth});rotate=function(){var triggerID=$active.attr("rel")- 1;var image_reelPosition=triggerID*imageWidth;$(".navi_links a").removeClass('active');$active.addClass('active');$(".desc").stop(true,true).slideUp('slow');$(".desc").eq($('.navi_links a.active').attr("rel")- 1).slideDown("slow");$(".scroll_items").animate({left:-image_reelPosition},970);};rotateSwitch=function(){$(".desc").eq($('.navi_links a.active').attr("rel")- 1).slideDown("slow");play=setInterval(function(){$active=$('.navi_links a.active').next();if($active.length===0){$active=$('.navi_links a:first');}
rotate();},70000);};rotateSwitch();$(".navi_links a").click(function(){$active=$(this);clearInterval(play);rotate();rotateSwitch();return false;});});
/*
     FILE ARCHIVED ON 14:41:53 Jan 02, 2017 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 08:04:44 May 27, 2017.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/